name: decimal
version: 1.5.0
description: >
  The decimal package allows you to deal with decimal numbers without losing
  precision.
repository: https://github.com/a14n/dart-decimal
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rational: ^1.2.1

dev_dependencies:
  expector: ^0.1.2
  intl: ^0.17.0
  test: ^1.17.2
