name: Go

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  push_core_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker build -t ghcr.io/jjchinnapat/imageflutterweb:latest --build-arg GIT_PAT=${{ secrets.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 }} .
        echo ${{ secrets.GIT_PAT }} | docker login ghcr.io -u jjchinnapat --password-stdin
        docker push ghcr.io/jjchinnapat/imageflutterweb:latest
