name: dartz
version: 0.10.1
homepage: https://github.com/spebbe/dartz
description: Functional Programming in Dart. Purify your Dart code using efficient immutable data structures, monads, lenses and other FP tools.
author: Björn Sperber <spebbe@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ">=1.17.1"
