name: generate_reflection
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.1.0
  build: ^2.0.0
  universal_html:
    path: '..'

dev_dependencies:
  build_runner: ^1.12.1
  build_web_compilers: ^2.16.5
  pedantic: ^1.11.0