name: flutter_dropzone_web
description: A drag-and-drop Flutter plugin (Web only).
version: 2.1.1
homepage: https://github.com/deakjahn/flutter_dropzone

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_dropzone_platform_interface: ^2.0.0
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterDropzonePlugin
        fileName: flutter_dropzone_plugin.dart

  assets:
    - packages/flutter_dropzone_web/assets/flutter_dropzone.js
